import { cn } from "@/lib/utils";
import { Flame, Sparkles, Star } from "lucide-react";
import type { ReactNode } from "react";

interface ChipProps {
  children: ReactNode;
  className?: string;
  title?: string;
}

export function Chip({ children, className, title }: ChipProps) {
  return (
    <span
      title={title}
      className={cn(
        "glass-chip inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-semibold text-slate-700",
        className,
      )}
    >
      {children}
    </span>
  );
}

export function XPBadge({
  xp,
  className,
}: {
  xp: number;
  className?: string;
}) {
  return (
    <Chip className={cn("text-slate-800", className)} title="Experience points">
      <Star className="size-3.5 fill-amber-400 text-amber-500" aria-hidden="true" />
      <span className="tabular-nums">{xp.toLocaleString()}</span>
      <span className="sr-only"> experience points</span>
      <span aria-hidden="true">XP</span>
    </Chip>
  );
}

export function StreakBadge({
  streak,
  className,
}: {
  streak: number;
  className?: string;
}) {
  return (
    <Chip className={className} title="Daily practice streak">
      <Flame
        className={cn(
          "size-3.5",
          streak > 0 ? "fill-orange-400 text-orange-500" : "text-slate-400",
        )}
        aria-hidden="true"
      />
      <span className="tabular-nums">{streak}</span>
      <span>{streak === 1 ? "day" : "days"}</span>
    </Chip>
  );
}

export function LevelBadge({
  level,
  title,
  className,
}: {
  level: number;
  title: string;
  className?: string;
}) {
  return (
    <span
      className={cn(
        "glass-chip inline-flex items-center gap-2 rounded-full py-1 pr-3.5 pl-1.5 text-xs font-semibold text-slate-700",
        className,
      )}
    >
      <span className="grid size-6 place-items-center rounded-full bg-gradient-to-br from-indigo-500 to-cyan-400 text-[10px] font-bold text-white">
        {level}
      </span>
      <span>LEVEL {level}</span>
      <span className="text-slate-400" aria-hidden="true">
        ·
      </span>
      <span className="text-slate-600">{title}</span>
    </span>
  );
}

const DIFFICULTY_TONES: Record<string, string> = {
  Easy: "bg-emerald-500/15 text-emerald-700 border-emerald-500/25",
  Medium: "bg-amber-400/20 text-amber-700 border-amber-500/25",
  Challenging: "bg-rose-500/15 text-rose-700 border-rose-500/25",
};

export function DifficultyBadge({
  difficulty,
  className,
}: {
  difficulty: string;
  className?: string;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center rounded-full border px-2.5 py-0.5 text-[11px] font-semibold",
        DIFFICULTY_TONES[difficulty] ??
          "border-slate-300/60 bg-slate-500/10 text-slate-600",
        className,
      )}
    >
      {difficulty}
    </span>
  );
}

export function LevelPill({
  level,
  className,
}: {
  level: "basic" | "intermediate";
  className?: string;
}) {
  const isBasic = level === "basic";
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-[11px] font-semibold",
        isBasic
          ? "border-teal-500/25 bg-teal-500/12 text-teal-700"
          : "border-indigo-500/25 bg-indigo-500/12 text-indigo-700",
        className,
      )}
    >
      <span
        className={cn(
          "size-1.5 rounded-full",
          isBasic ? "bg-teal-500" : "bg-indigo-500",
        )}
        aria-hidden="true"
      />
      {isBasic ? "BASIC" : "INTERMEDIATE"}
    </span>
  );
}

export function AiModeBadge({
  aiEnabled,
  className,
}: {
  aiEnabled: boolean;
  className?: string;
}) {
  return (
    <Chip
      className={cn("gap-1", className)}
      title={
        aiEnabled
          ? "Conversation is generated by the configured AI provider"
          : "Conversation follows the scripted practice questions — no AI provider is connected"
      }
    >
      <Sparkles
        className={cn(
          "size-3.5",
          aiEnabled ? "text-indigo-500" : "text-slate-400",
        )}
        aria-hidden="true"
      />
      {aiEnabled ? "AI coach" : "Practice mode"}
    </Chip>
  );
}
